export interface IExportDeviceType {
	DeviceName: string
	DeviceInfoId: string
	ExportLabId?: string
	QuantityOriginal: Number
	ExpRegGeneralId?: string
	Unit: string
	DeviceDetailId?: string
	SerialNumber?: string
	ManufacturingDate?: string
	DateMaintenace?: string
	StartGuarantee?: string
	EndGuarantee?: string
	YearStartUsage?: Number
	HoursUsage?: Number
	Quantity?: Number
	LabId?: string
	LabName?: string
	Location?: string
	ExportDate?: string
	DateTranferTo?: string
	DateStartUsage?: string
	HoursUsageTotal?: Number
	PeriodicMaintenance?: Number
	EmployeeName?: string
	ExportId?: string
	WarningMaintenace?: string
	Status?: string
	InstrumentDeptId?: string
	DeviceId: string
	DeviceEnglishName: string
	Specification: string
	Manufacturer: string
	Origin: string
	SupplierName: string
	QuantityImport: Number
	QuantityDistribute: Number
	QuantityExport: Number
	QuantityAvailable: Number
	DepartmentImportName: string
	DateImport: string
	DateMaintenance: string
	DepartmentImportId: string
	DepartmentMaintenanceId: string
	DepartmentMaintenanceName: string
	Model: string
	SupplierId: Number
	WarningMaintenance: string
}

export const dummyExportDevice: IExportDeviceType = {
	DeviceName: '',
	DeviceInfoId: '',
	QuantityOriginal: 0,
	Unit: '',
	DeviceDetailId: '',
	SerialNumber: '',
	ManufacturingDate: '',
	StartGuarantee: '',
	DateMaintenace: '',
	EndGuarantee: '',
	YearStartUsage: 0,
	HoursUsage: 0,
	Quantity: 0,
	LabId: '',
	LabName: '',
	Location: '',
	ExportDate: '',
	DateTranferTo: '',
	EmployeeName: '',
	ExportId: '',
	ExportLabId: '',
	DateStartUsage: '',
	ExpRegGeneralId: '',
	HoursUsageTotal: 0,
	PeriodicMaintenance: 0,
	WarningMaintenace: '',
	DeviceId: "",
	DeviceEnglishName: "",
	Specification: "",
	Manufacturer: "",
	Origin: "",
	SupplierName: "",
	QuantityImport: 0,
	QuantityDistribute: 0,
	QuantityExport: 0,
	QuantityAvailable: 0,
	DepartmentImportName: "",
	DateImport: "",
	DateMaintenance: "",
	DepartmentImportId: "",
	DepartmentMaintenanceId: "",
	DepartmentMaintenanceName: "",
	Model: "",
	SupplierId: 0,
	WarningMaintenance: "",
};

export interface IExportInstrument {
	ExportId: string;
	DeviceName: string;
	InstrumentDeptId: string;
	QuantityOriginal: Number;
	Unit: string;
	DeviceDetailId: string;
}
